// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotorDecisao.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MotorDecisao.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MotorDecisaoDbContext))]
    [Migration("20260924191054_AddGlobalVariables")]
    partial class AddGlobalVariables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("usebens_motor_decisao")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MotorDecisao.Domain.Entities.DecisionExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("FlowVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("InputData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Justifications")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("Limit")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Outputs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ProposalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FlowVersionId");

                    b.HasIndex("ProposalReference");

                    b.ToTable("decision_executions", "usebens_motor_decisao");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.DecisionFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("decision_flows", "usebens_motor_decisao");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.ExecutionTrace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Fluxo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DecisionExecutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb");

                    b.Property<string>("Expression")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("NodeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NodeLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DecisionExecutionId", "Sequence");

                    b.ToTable("execution_traces", "usebens_motor_decisao");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.FlowEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EdgeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("FlowVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceHandle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceNodeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TargetNodeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FlowVersionId", "EdgeKey")
                        .IsUnique();

                    b.ToTable("flow_edges", "usebens_motor_decisao");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.FlowNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FlowVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NodeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("RulesetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId");

                    b.HasIndex("FlowVersionId", "NodeKey")
                        .IsUnique();

                    b.ToTable("flow_nodes", "usebens_motor_decisao");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.FlowVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeLog")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DecisionFlowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DecisionFlowId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("flow_versions", "usebens_motor_decisao");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.Formula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("FlowVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FlowVersionId", "Key")
                        .IsUnique();

                    b.ToTable("formulas", "usebens_motor_decisao");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.GlobalVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("global_variables", "usebens_motor_decisao");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.InputField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FlowVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<bool>("Required")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FlowVersionId", "Name")
                        .IsUnique();

                    b.ToTable("input_fields", "usebens_motor_decisao");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionExpression")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ForcedOutcome")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RulesetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ScoreWeight")
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId", "Order");

                    b.ToTable("rules", "usebens_motor_decisao");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.Ruleset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ApprovalThreshold")
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("FlowVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FlowVersionId");

                    b.ToTable("rulesets", "usebens_motor_decisao");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.DecisionExecution", b =>
                {
                    b.HasOne("MotorDecisao.Domain.Entities.FlowVersion", "FlowVersion")
                        .WithMany()
                        .HasForeignKey("FlowVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FlowVersion");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.ExecutionTrace", b =>
                {
                    b.HasOne("MotorDecisao.Domain.Entities.DecisionExecution", "DecisionExecution")
                        .WithMany("Trace")
                        .HasForeignKey("DecisionExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecisionExecution");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.FlowEdge", b =>
                {
                    b.HasOne("MotorDecisao.Domain.Entities.FlowVersion", "FlowVersion")
                        .WithMany("Edges")
                        .HasForeignKey("FlowVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowVersion");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.FlowNode", b =>
                {
                    b.HasOne("MotorDecisao.Domain.Entities.FlowVersion", "FlowVersion")
                        .WithMany("Nodes")
                        .HasForeignKey("FlowVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotorDecisao.Domain.Entities.Ruleset", "Ruleset")
                        .WithMany()
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FlowVersion");

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.FlowVersion", b =>
                {
                    b.HasOne("MotorDecisao.Domain.Entities.DecisionFlow", "DecisionFlow")
                        .WithMany("Versions")
                        .HasForeignKey("DecisionFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecisionFlow");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.Formula", b =>
                {
                    b.HasOne("MotorDecisao.Domain.Entities.FlowVersion", "FlowVersion")
                        .WithMany()
                        .HasForeignKey("FlowVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowVersion");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.InputField", b =>
                {
                    b.HasOne("MotorDecisao.Domain.Entities.FlowVersion", "FlowVersion")
                        .WithMany("InputFields")
                        .HasForeignKey("FlowVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowVersion");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.Rule", b =>
                {
                    b.HasOne("MotorDecisao.Domain.Entities.Ruleset", "Ruleset")
                        .WithMany("Rules")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.Ruleset", b =>
                {
                    b.HasOne("MotorDecisao.Domain.Entities.FlowVersion", "FlowVersion")
                        .WithMany("Rulesets")
                        .HasForeignKey("FlowVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowVersion");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.DecisionExecution", b =>
                {
                    b.Navigation("Trace");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.DecisionFlow", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.FlowVersion", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("InputFields");

                    b.Navigation("Nodes");

                    b.Navigation("Rulesets");
                });

            modelBuilder.Entity("MotorDecisao.Domain.Entities.Ruleset", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
